// Credits & licences, reached from About (a sheet on iOS, a page on the web). Credits holds the attributions the
// data licences require. The licence list is generated by scripts/gen-licenses.mjs from the packages that ship in
// this build. Each entry opens to its full licence text; texts are shared by index to keep the file small.
import { useState } from 'react';
import { Linking, Platform, Pressable, View } from 'react-native';

import { Card } from '@/components/bits';
import { Icon } from '@/components/icon';
import { SheetFrame } from '@/components/sheet';
import { T } from '@/components/text';
import licenses from '@/data/licenses.json';
import { usePalette } from '@/state/app';

interface Entry {
  name: string;
  version: string | null;
  license: string;
  url: string | null;
  platforms: string[];
  note?: string;
  text: number | null;
}

const REPO = 'https://github.com/prompt-janitor/tree-of-bob';
const BY_SA_3 = 'https://creativecommons.org/licenses/by-sa/3.0/';
const BY_SA_4 = 'https://creativecommons.org/licenses/by-sa/4.0/';

interface Credit {
  text: string;
  links: { label: string; url: string }[];
}

const CREDITS: Credit[] = [
  { text: 'Story data adapted from the Bobiverse Wiki (CC BY-SA 3.0).', links: [{ label: 'Bobiverse Wiki', url: 'https://bobiverse.fandom.com' }, { label: 'CC BY-SA 3.0', url: BY_SA_3 }] },
  { text: "This app's data file: CC BY-SA 4.0.", links: [{ label: 'Data file', url: `${REPO}/blob/main/src/data/tree-of-bob.json` }, { label: 'CC BY-SA 4.0', url: BY_SA_4 }] },
  { text: 'Star positions: HYG Database v4.1, CC BY-SA 4.0. Some far positions: SIMBAD, Wikipedia.', links: [{ label: 'HYG Database', url: 'https://codeberg.org/astronexus/hyg' }] },
  { text: 'Some lineage cross-checked against bobiverse-map by thunfischtoast, CC BY-SA 4.0.', links: [{ label: 'bobiverse-map', url: 'https://github.com/thunfischtoast/bobiverse-map' }] },
  { text: 'App code © 2026 Chun Wong, MIT licence.', links: [{ label: 'Source code', url: REPO }] },
];

const hostOf = (url: string) => url.replace(/^https?:\/\//, '').replace(/\/$/, '');

function LinkText({ label, url }: { label: string; url: string }) {
  const p = usePalette();
  return (
    <Pressable
      onPress={() => Linking.openURL(url).catch(() => {})}
      accessibilityRole="link"
      accessibilityLabel={`${label}, ${hostOf(url)}`}
      accessibilityHint="Opens in your web browser"
      style={({ pressed }) => ({ minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 4, opacity: pressed ? 0.6 : 1 })}>
      <T variant="secondary" weight="600" style={{ textDecorationLine: 'underline' }}>{label}</T>
      <Icon name="arrow" size={14} color={p.ink2} />
    </Pressable>
  );
}

function Credits() {
  const p = usePalette();
  return (
    <View style={{ gap: 8 }}>
      <T variant="row" accessibilityRole="header">Credits</T>
      <Card>
        {CREDITS.map((c, i) => (
          <View key={c.text} style={{ paddingHorizontal: 14, paddingTop: 10, borderTopWidth: i === 0 ? 0 : 1, borderColor: p.line2 }}>
            <T variant="secondary" tone="ink2" selectable>{c.text}</T>
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', columnGap: 16 }}>
              {c.links.map((l) => <LinkText key={l.url} label={l.label} url={l.url} />)}
            </View>
          </View>
        ))}
      </Card>
    </View>
  );
}

const data = licenses as { fonts: Entry[]; notices: Entry[]; packages: Entry[]; texts: string[] };
const platform = Platform.OS === 'web' ? 'web' : 'native';
const here = (list: Entry[]) => list.filter((e) => e.platforms.includes(platform));

function Row({ entry, first, open, onToggle }: { entry: Entry; first: boolean; open: boolean; onToggle: () => void }) {
  const p = usePalette();
  const text = entry.text == null ? null : data.texts[entry.text];
  const title = entry.version ? `${entry.name} ${entry.version}` : entry.name;
  return (
    <View style={{ borderTopWidth: first ? 0 : 1, borderColor: p.line2 }}>
      <Pressable
        onPress={onToggle}
        accessibilityRole="button"
        accessibilityLabel={`${title}, ${entry.license}`}
        accessibilityHint={open ? 'Hides the licence text' : 'Shows the licence text'}
        accessibilityState={{ expanded: open }}
        style={({ pressed }) => ({ minHeight: 44, paddingHorizontal: 14, paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 10, opacity: pressed ? 0.6 : 1 })}>
        <View style={{ flex: 1, gap: 2 }}>
          <T variant="secondary" weight="600">{title}</T>
          <T variant="data" tone="ink3">{entry.license}</T>
        </View>
        <Icon name={open ? 'chevronDown' : 'chevronRight'} size={18} color={p.ink2} />
      </Pressable>
      {open ? (
        <View style={{ paddingHorizontal: 14, paddingBottom: 14, gap: 8 }}>
          {entry.note ? <T variant="secondary" tone="ink2">{entry.note}</T> : null}
          {entry.url ? <T variant="data" tone="ink2" selectable>{entry.url}</T> : null}
          <T variant="data" tone="ink2" selectable style={{ fontSize: 11, lineHeight: 15 }}>
            {text ?? `This package ships no licence file. Its package.json declares the ${entry.license} licence.`}
          </T>
        </View>
      ) : null}
    </View>
  );
}

function Section({ title, entries, open, toggle }: { title: string; entries: Entry[]; open: Set<string>; toggle: (k: string) => void }) {
  if (!entries.length) return null;
  return (
    <View style={{ gap: 8 }}>
      <T variant="row" accessibilityRole="header">{`${title} (${entries.length})`}</T>
      <Card>
        {entries.map((e, i) => {
          const k = `${title}:${e.name}@${e.version ?? ''}`;
          return <Row key={k} entry={e} first={i === 0} open={open.has(k)} onToggle={() => toggle(k)} />;
        })}
      </Card>
    </View>
  );
}

export default function LicensesSheet() {
  const [open, setOpen] = useState<Set<string>>(() => new Set());
  const toggle = (k: string) =>
    setOpen((prev) => {
      const next = new Set(prev);
      if (next.has(k)) next.delete(k);
      else next.add(k);
      return next;
    });
  return (
    <SheetFrame title="Credits & licences">
      <Credits />
      <T variant="secondary" tone="ink2">Open-source software and fonts in this app. Tap one for its licence.</T>
      <Section title="Fonts" entries={here(data.fonts)} open={open} toggle={toggle} />
      <Section title="Graphics engine" entries={here(data.notices)} open={open} toggle={toggle} />
      <Section title="Packages" entries={here(data.packages)} open={open} toggle={toggle} />
    </SheetFrame>
  );
}
